### ISSUE TITLE
branch naming and usage

### ISSUE THREAD

**Issue by kyle-github** [laurium-labs/PLCTag.jl#6]
Since I just managed to put a broken version of 2.1.7 out on master, I will take this a kick in the pants to actually redo my branch use that I've been thinking about for a while.

Starting soon (probably this weekend), I will create some new branches in the core library repo:

release - the real main branch.   Nothing goes here except tested code that has "soaked" for a while as a pre-release unless it is an urgent bug fix or such a narrow change that the risk is small.  I will make this the default branch so that when people check out the code without specifying a branch, this is what they get.

prerelease - once I am done with my development and tests, I will merge to prerelease.  All prerelease drops will come from this branch.   When these are validated with more testing and a lack of user bugs, I will merge this over to release.

I am not sure what to do with the master branch.   I will try to keep it up to date with release for a while, but generally I would like to drop it.

How much heartburn will this give you guys?

**Comment by kyle-github** [comment]
Note that I would appreciate feedback from you when there is a prerelease: does it break something in your wrapper/tooling/plans etc?   I want to know that so that I can fix it before a full release.

**Comment by krrutkow** [comment]
@kyle-github PLCTag.jl is only building against published source tarballs, so there shouldn't be a problem unless there is a breaking change to the C API.  I will work on getting the Julia package testing set up though so whenever you publish a (pre-)release of libplctag the tests can be triggered against it.  I found the test server in libplctag, and will proceed to use that for package testing.

**Comment by kyle-github** [comment]
OK.  The test server is very... limited.   Single process, no threading.   But I do use it to help test and it does sometimes catch something.   The goal behind it was that as I found bugs that could only be checked with hardware I do not have, I would add the test cases to the simulator.

**Comment by krrutkow** [comment]
Yeah, I kind of discovered that...  As all good developers do, I made my tests only hit the cases that the server gave the right answers for! =P

**Comment by krrutkow** [comment]
@kyle-github The following GitHub Apps will need to be installed for the organization.  You can probably only grant them access to this repo as well.  Thanks!

- AppVeyor
- Travis CI
- Julia TagBot
- JuliaTeam Registrator

**Comment by kyle-github** [comment]
I enabled local and third party GitHub actions too.  I installed AppVeyor and Travis CI.   I found an app for Julia TagBot but I could not figure out how to install it.   I did not find JuliaTeam Registrator but no app.   I found a JuliaRegistries/Registrator.jl repo. 

Let me know what I am doing wrong for the last two.   I thought that there would be something to turn on at least, but all I find are repos or, in the case of the TagBot app, just instructions on how to use it.   I guess it just works?

**Comment by krrutkow** [comment]
Ahh, sorry... TagBot has changed to being a GitHub Action now, so that was just a legacy app.  You are correct, the Registrator.jl repo has an installation link:  https://github.com/apps/juliateam-registrator/installations/new  Shouldn't really have to do anything other than install and grant access, everything they do is based on events from mentions, creating PRs, merges, etc., and they use config files saved in each repo.  Thanks again!

**Comment by krrutkow** [comment]
Linux/OSX tests are now hooked up, and the package is in the registration process.  Next step would be to figure out how creating a release of libplctag can trigger a build of PLCTag with the environment variable `LIBPLCTAG_VERSION="2.1.8"` specifying the (pre-)release to test against.  For now we could perform a manual step of updating `.github/workflows/CI.yml` to test a particular set of versions.

**Comment by kyle-github** [comment]
Maybe we could just tie the CI jobs together?   That might be too much coupling between the projects...

In my C code, I have started adding checks for specific API versions.  The library now provides functions to let you check for semver-style compatibility.

Let me know if you have any ideas on how to make it more automatic and driven by the core library tagging.   I will try to implement whatever you need to make it easier.
